name: Merge Separated Files

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  merge_and_upload:
    name: Merge JSON files and Upload
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Merge JSON files
        run: python3 merge.py

    - name: Commit changes
      run: |
        current_date=$(date +'%d/%m/%Y, %H:%M')
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add -A
        git commit -m "Update: $current_date"
        
    - name: Push changes
      run: |
        git push https://${{ secrets.GH_TOKEN }}@github.com/elbkr/bad-websites.git
